### ISSUE TITLE
Time in PICU Scoring

### ISSUE THREAD

**Issue by ljwoodley** [ctsit/psofa#6]
Create summary outputs for total time spent in PICU/PCICU.

**Comment by jameslwynn** [comment]
This is great... We will want to include the max pSOFA, Max VIS in first hour and first 2 hours after admission to PICU or PCICU. I am hoping that the max value in the first hour is not substantially different that the max in the first 2 hours. It is possible the charting/labs that makes the values possible will not be complete in only the first hour. A change in pSOFA and components/VIS in the first "X" hours (don't know what time window yet but am considering 6, 12,& 24 hours) after admission is also likely important to identify those at greatest risk of mortality.
